language: node_js

node_js:
  - node

install: 
  - npm ci

script: 
  - npm run test
  - npm run build

deploy:
  provider: s3
  access_key_id: "AKIAJZWAXKYVVJAHVJLQ"
  secret_access_key: "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"
  bucket: "S3 Bucket"